#!/bin/bash

# Define version and architecture
VERSION="3.5"
ARCH="arm64"
DEB_FILE="pifan_${VERSION}_${ARCH}.deb"
# Update this URL to point to your actual release
DOWNLOAD_URL="https://github.com/temidaradev/PiFan/releases/download/v${VERSION}/${DEB_FILE}"

# Install dependencies
sudo apt update
sudo apt install -y python3-pil python3-packaging rpi.gpio-common wget

# Download the .deb package
wget "$DOWNLOAD_URL" || error "Failed to download $DEB_FILE"

# Install the package
sudo dpkg -i "$DEB_FILE" || sudo apt-get -f install -y || error "Failed to install pifan"

# Clean up
rm -f "$DEB_FILE"
